### ISSUE TITLE
Would like to see test cases

### ISSUE THREAD

**Issue by jedahan** [apeduru/bspl#1]
Tests for order of operations would be cool

I wonder what else

**Comment by apeduru** [comment]
@jedahan Unit tests are in the works. I am also rewriting the lexer as it is far too convoluted atm.

**Comment by apeduru** [comment]
Unit tests added in this [commit](https://github.com/apeduru/bspl/commit/adc58a2751ca94ab50210ad7d76992a5bf6c366e).

**Comment by jedahan** [comment]
nice!
